# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 493)
        MainWindow.setStyleSheet("alternate-background-color: rgb(85, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 651, 501))
        self.frame.setStyleSheet("\n"
"background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(310, 10, 331, 251))
        self.frame_2.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(60, 0, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(20, 20, 271, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(10, 220, 311, 24))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.horizontalSlider = QtWidgets.QSlider(self.widget1)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid  rgb(255, 0, 0);\n"
"    height: 4px;\n"
"    background: rgb(255, 0, 0);\n"
"\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"    width: 28px;\n"
"    height:28px;\n"
"\n"
"left: 11px;\n"
"right: 11px;\n"
"\n"
"\n"
"    margin: -12px;\n"
"    border-radius:14px;\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal{\n"
"background-color:white;\n"
"border: 1px solid white;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(310, 270, 331, 181))
        self.frame_3.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget2 = QtWidgets.QWidget(self.frame_3)
        self.widget2.setGeometry(QtCore.QRect(10, 40, 311, 61))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_2.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color:rgb(255, 0, 0);")
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_3.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"\n"
"color:rgb(255, 0, 0);")
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.widget2)
        self.pushButton.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"\n"
"color:rgb(255, 0, 0);")
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.widget3 = QtWidgets.QWidget(self.frame_3)
        self.widget3.setGeometry(QtCore.QRect(30, 10, 291, 21))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 130, 91, 51))
        self.pushButton_5.setStyleSheet("\n"
"color:rgb(255, 0, 0);")
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 130, 81, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"\n"
"color:rgb(255, 0, 0);")
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 91, 16))
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(180, 110, 91, 16))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 8pt \"Gill Sans Ultra Bold\";")
        self.label_5.setObjectName("label_5")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 291, 441))
        self.listWidget.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Myanmar Text\";")
        self.listWidget.setObjectName("listWidget")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.listWidget.raise_()
        self.frame.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.horizontalSlider.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Información de la Cancion"))
        self.label_7.setText(_translate("MainWindow", "00:00"))
        self.label_8.setText(_translate("MainWindow", "00:00"))
        self.pushButton_2.setText(_translate("MainWindow", "|<<"))
        self.pushButton_3.setText(_translate("MainWindow", "||"))
        self.pushButton.setText(_translate("MainWindow", ">>|"))
        self.label.setText(_translate("MainWindow", "Atrás"))
        self.label_2.setText(_translate("MainWindow", "Pausa"))
        self.label_3.setText(_translate("MainWindow", "Adelante"))
        self.pushButton_5.setText(_translate("MainWindow", "[_]"))
        self.pushButton_4.setText(_translate("MainWindow", "<-->"))
        self.label_4.setText(_translate("MainWindow", "Aleatorio"))
        self.label_5.setText(_translate("MainWindow", "Reiniciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())